spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=licenta_db;encrypt=true;trustServerCertificate=true;}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# ==========================================
# 2. APPLICATION SPECIFIC
# ==========================================
app.forecast.csv-path=${CSV_PATH:E:\\An3\\Licenta-doc\\Prognoze\\PrognozaDeVenit.csv}

# ==========================================
# 3. SECURITY & AUTHENTICATION
# ==========================================
jwt.secret-key=${JWT_SECRET}

# Admin Seeder Credentials
admin.default.email=${ADMIN_EMAIL:admin@quickshift.com}
admin.default.password=${ADMIN_PASSWORD}

# ==========================================
# 4. EMAIL
# ==========================================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=${MAIL_FROM:${MAIL_USERNAME}}
app.frontend.url=${FRONTEND_URL:http://localhost:5173}