spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=licenta_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

app.forecast.csv-path=E:\\An3\\Licenta\\PrognozaDeVenit.csv