spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=licenta_db;encrypt=true;trustServerCertificate=true;}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# ==========================================
# 2. APPLICATION SPECIFIC
# ==========================================
app.forecast.csv-path=${CSV_PATH:E:\\An3\\Licenta\\PrognozaDeVenit.csv}

# ==========================================
# 3. SECURITY & AUTHENTICATION
# ==========================================
jwt.secret-key=${JWT_SECRET}

# Admin Seeder Credentials
admin.default.email=${ADMIN_EMAIL:admin@quickshift.com}
admin.default.password=${ADMIN_PASSWORD}